# Generated by Django 4.0 on 2025-01-23 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('mrn', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('kebele', models.CharField(blank=True, max_length=255, null=True)),
                ('ethiopian_date', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('mode_of_delivery', models.CharField(choices=[('svd', 'SVD'), ('cs', 'Caesarean Section (C/S)'), ('forceps', 'Forceps/Vacuum Extraction'), ('episiotomy', 'Episiotomy'), ('other', 'Other Procedures')], max_length=20)),
                ('maternal_status', models.CharField(choices=[('unstable', 'Unstable/Deteriorated and Referred'), ('stable', 'Stable'), ('died', 'Died')], max_length=20)),
                ('obstetric_complications', models.CharField(blank=True, choices=[('pre_eclampsia', 'Pre-eclampsia'), ('eclampsia', 'Eclampsia'), ('aph', 'APH'), ('pph', 'PPH'), ('other', 'Other Obstetric Complications'), ('referred', 'Referred')], max_length=20, null=True)),
                ('alive', models.BooleanField()),
                ('APGAR_score_1_5', models.CharField(max_length=7)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('weight_in_grams', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('stillbirth', models.PositiveIntegerField(blank=True, choices=[(1, 'Fresh'), (2, 'Macerated')], null=True)),
                ('live_birth_died_before_arrival', models.BooleanField(blank=True, null=True)),
                ('live_birth_died_after_arrival_or_delivery', models.BooleanField(blank=True, null=True)),
                ('mrn_newborn', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('vitamin_k', models.BooleanField(blank=True, null=True)),
                ('ttc_eye_ointment', models.BooleanField(blank=True, null=True)),
                ('bcg_given', models.BooleanField(blank=True, null=True)),
                ('opv_given', models.BooleanField(blank=True, null=True)),
                ('hiv_test_accepted', models.BooleanField()),
                ('hiv_retesting_accepted', models.BooleanField(blank=True, null=True)),
                ('hiv_test_result', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown')], max_length=8, null=True)),
                ('known_hiv_positive', models.BooleanField(blank=True, null=True)),
                ('target_population_category', models.CharField(blank=True, max_length=255, null=True)),
                ('hiv_positive_delivery_link', models.CharField(blank=True, choices=[('1', 'Same Facility'), ('2', 'Other Facility')], max_length=1, null=True)),
                ('counseled_on_feeding_options', models.BooleanField(blank=True, null=True)),
                ('mothers_art_regimen', models.CharField(blank=True, max_length=255, null=True)),
                ('newborn_nvp', models.CharField(blank=True, max_length=255, null=True)),
                ('managed_by', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to='auth.user')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to='auth.user')),
            ],
            options={
                'verbose_name': 'Delivery Record',
                'verbose_name_plural': 'Delivery Records',
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['mrn'], name='core_delive_mrn_3d48e2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['name'], name='core_delive_name_f71adb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['mode_of_delivery'], name='core_delive_mode_of_014553_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['maternal_status'], name='core_delive_materna_3d8d16_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['delivery_date'], name='core_delive_deliver_1abe08_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['alive'], name='core_delive_alive_572b57_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['sex'], name='core_delive_sex_a5d220_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['hiv_test_result'], name='core_delive_hiv_tes_4059f3_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['delivery_date', 'maternal_status'], name='core_delive_deliver_603b90_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['delivery_date', 'mode_of_delivery'], name='core_delive_deliver_59d0a4_idx'),
        ),
    ]
